<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenusTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('menus')->insert([
            ['kode_menu' => 'MN00', 'nama' => 'Buku Tanah Permai', 'harga' => '3500', 'gambar' => 'bukutp.jpg', 'kategori' => 'ATK', 'stok' => 0],
            ['kode_menu' => 'MN01', 'nama' => 'Sampul Buku Tanah Permai', 'harga' => '2000', 'gambar' => 'sampulbukutp.jpg', 'kategori' => 'ATK', 'stok' => 49],
            ['kode_menu' => 'MN02', 'nama' => 'Buku Pedoman', 'harga' => '8000', 'gambar' => 'bukupedoman.jpg', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN03', 'nama' => 'Buku Izin', 'harga' => '7000', 'gambar' => 'bukuizin.jpg', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN04', 'nama' => 'Buku Tutur Sabda', 'harga' => '9000', 'gambar' => 'bukuts.jpg', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN05', 'nama' => 'Buku Doa', 'harga' => '6000', 'gambar' => 'bukudoa.jpg', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN06', 'nama' => 'Buku Kejar Berita', 'harga' => '8000', 'gambar' => 'bukukb.jpg', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN07', 'nama' => 'Buku Kas', 'harga' => '4000', 'gambar' => 'bukukas.jpg', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN08', 'nama' => 'HYMNS', 'harga' => '305500', 'gambar' => 'hymns.png', 'kategori' => 'Buku Rohani', 'stok' => 1],
            ['kode_menu' => 'MN09', 'nama' => 'Alkitab Perjanjian Baru Versi Inggris Dengan Catatan Kaki', 'harga' => '197500', 'gambar' => 'ntrvev.jpg', 'kategori' => 'Buku Rohani', 'stok' => 1],
            ['kode_menu' => 'MN10', 'nama' => 'Alkitab Perjanjian Baru Versi Inggris Tanpa Catatan Kaki', 'harga' => '100000', 'gambar' => 'ntrcevwfn.jpg', 'kategori' => 'Buku Rohani', 'stok' => 1],
            ['kode_menu' => 'MN11', 'nama' => 'Kidung Pemulihan', 'harga' => '207000', 'gambar' => 'kidung.jpg', 'kategori' => 'Buku Rohani', 'stok' => 1],
            ['kode_menu' => 'MN12', 'nama' => 'Alkitab Versi Pemulihan Perjanjian Lama dan Perjanjian Baru', 'harga' => '350000', 'gambar' => 'avpplpb.jpeg', 'kategori' => 'Buku Rohani', 'stok' => 1],
            ['kode_menu' => 'MN13', 'nama' => 'Pen Hi-Tech Kenko Hitam Gel 0.28mm', 'harga' => '2000', 'gambar' => 'penhi-techkenko.jpeg', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN14', 'nama' => 'Pen Hi Tech C 0,3', 'harga' => '21000', 'gambar' => 'pulpenhitechc0,3.jpg', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN15', 'nama' => 'Pen I Tech Jocyo-2', 'harga' => '2500', 'gambar' => 'itech2joyco.jpeg', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN16', 'nama' => 'Refill Isi Pen Hi Tech C Pilot', 'harga' => '14000', 'gambar' => 'refillisipenhitechcpilot.jpeg', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN17', 'nama' => 'Pen Kokoro', 'harga' => '5000', 'gambar' => 'pengelkokoro.JPEG', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN18', 'nama' => 'Pen Uni Jestream Ballpoint 0,38mm', 'harga' => '21000', 'gambar' => 'penunijetstreamballpoint0,38mm.jpg', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN19', 'nama' => 'Refill Pen Uni Jetstream 0.38mm', 'harga' => '15000', 'gambar' => 'refillisipenunijetstream0.38mm.jpeg', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN20', 'nama' => 'Refill Pen I Tech Jocyo 0.28mm', 'harga' => '2000', 'gambar' => 'refillisipenitechjoyco0.28mm.jpeg', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN21', 'nama' => 'Penanda KENKO Highlighter Dreamliner', 'harga' => '3500', 'gambar' => 'penandakenkohighlighterdreamliner.jpeg', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN22', 'nama' => 'Penanda KENKO Highlighter Softliner', 'harga' => '3500', 'gambar' => 'penandakenkohighlightersoftliner.jpeg', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN23', 'nama' => 'Joyco Quaco 4 Warna 0.7', 'harga' => '5500', 'gambar' => 'joykoquaco0.7.jpeg', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN24', 'nama' => 'Mechanical Pencil Pensil Mekanik Joyko MP-54 0.5 mm', 'harga' => '6000', 'gambar' => 'penciljoykomp540.5mm.jpeg', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN25', 'nama' => 'Pulpen Gel Joyko Diamond Art', 'harga' => '2500', 'gambar' => 'pulpengeljoykodiamondart.jpeg', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN26', 'nama' => 'Snowman Coloring Marker', 'harga' => '1500', 'gambar' => 'SnowmanColoringMarker.jpg', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN27', 'nama' => 'Joyko Permanent Marker Spidol', 'harga' => '4000', 'gambar' => 'joykopermanentmarkerspidol.jpeg', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN28', 'nama' => 'PILOT - Pen Ballpoint BPT-P', 'harga' => '2000', 'gambar' => 'penpilotbptp.JPG', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN29', 'nama' => 'Ballpobalpoint Faster - Pulpen Faster C600', 'harga' => '2500', 'gambar' => 'pulpenfasterc6.JPG', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN30', 'nama' => 'Penggaris Butterfly 15cm', 'harga' => '2000', 'gambar' => 'penggarisbutterfly15cm.jpeg', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN31', 'nama' => 'Penggaris Butterfly 20cm', 'harga' => '3000', 'gambar' => 'penggarisbutterfly20cm.jpeg', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN32', 'nama' => 'Penggaris Butterfly 30cm', 'harga' => '4000', 'gambar' => 'penggarisbutterfly30cm.jpeg', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN33', 'nama' => 'Penggaris Joyko 15cm', 'harga' => '2000', 'gambar' => 'penggarisjoyko15cm.jpeg', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN34', 'nama' => 'Folder A4 Dua Resleting Jaring Mesh Transparan (Carrier)', 'harga' => '20000', 'gambar' => 'tascarrier.jpeg', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN35', 'nama' => 'Kertas Kado Gulung Bes Wag', 'harga' => '5000', 'gambar' => 'kertaskadogulung.jpg', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN36', 'nama' => 'Clear Holder Joyko DK-B20F4 Folio 20 Lbr Document Keeper Folder', 'harga' => '19500', 'gambar' => 'clearholder.JPEG', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN37', 'nama' => 'Map Plastik Kancing folio f4', 'harga' => '4000', 'gambar' => 'mapplastik.JPEG', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN38', 'nama' => 'Dasi', 'harga' => '20000', 'gambar' => 'dasi.JPG', 'kategori' => 'Living', 'stok' => 1],
            ['kode_menu' => 'MN39', 'nama' => '70 Gsm A4 Copy Paper - Color: White (HVS)', 'harga' => '200', 'gambar' => 'hvs.jpg', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN40', 'nama' => 'Jaket FTTI', 'harga' => '190000', 'gambar' => '', 'kategori' => 'Living', 'stok' => 1],
            ['kode_menu' => 'MN41', 'nama' => 'Tokyo 1 Alas Gosok Ironing Cloth', 'harga' => '0', 'gambar' => 'alasgosok.JPEG', 'kategori' => 'Living', 'stok' => 1],
            ['kode_menu' => 'MN42', 'nama' => 'Ganso Laundry Bag 50CM x 60CM - M369', 'harga' => '20000', 'gambar' => 'laundrybags.JPEG', 'kategori' => 'Living', 'stok' => 50],
            ['kode_menu' => 'MN43', 'nama' => 'Nathalie Kaos dalam Katun Wanita NTA0027 Singlet Wanita', 'harga' => '21000', 'gambar' => 'bajudalamwanita.JPEG', 'kategori' => 'Living', 'stok' => 1],
            ['kode_menu' => 'MN44', 'nama' => 'Kaos Dalam Swan Brand', 'harga' => '21000', 'gambar' => 'bajudalampria.JPEG', 'kategori' => 'Living', 'stok' => 1],
            ['kode_menu' => 'MN45', 'nama' => 'Kaos Singlet Crocodile', 'harga' => '36000', 'gambar' => 'bajudalampriacrocodile.JPEG', 'kategori' => 'Living', 'stok' => 1],
            ['kode_menu' => 'MN46', 'nama' => 'Kertas Kado', 'harga' => '1500', 'gambar' => 'kertaskado.JPEG', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN47', 'nama' => 'Binder A5', 'harga' => '15000', 'gambar' => 'bindera5.JPG', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN48', 'nama' => 'Sidu Double Folio', 'harga' => '3000', 'gambar' => 'sidudoublefolio.png', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN49', 'nama' => 'Binder B5 Warna Cover Tebal Wengu Binder Plastik', 'harga' => '42000', 'gambar' => 'binderb5.JPEG', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN50', 'nama' => 'Bantex A5 Pastel Trendy Multi Ring Binder 20 Hole', 'harga' => '19000', 'gambar' => 'bantexa5.JPEG', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN51', 'nama' => 'Buku Tulis Sidu 38 Lembar', 'harga' => '3500', 'gambar' => 'bukutulissidu38.JPEG', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN52', 'nama' => 'Loose Leaf B5 100 Lembar Putih Polos', 'harga' => '10000', 'gambar' => 'looseleafb5polos.JPEG', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN53', 'nama' => 'LOOSE LEAF BIG BOSS GARIS A5-50 PUTIH', 'harga' => '5000', 'gambar' => 'looseleafa5bergaris.JPEG', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN54', 'nama' => 'Loose Leaf Joyko A5-7020 kertas bergaris/putih (100lbr)', 'harga' => '9000', 'gambar' => 'looseleafa5bergarisjoyko.JPEG', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN55', 'nama' => 'Loose Leaf B5 Bergaris Big Boss', 'harga' => '5500', 'gambar' => 'looseleafb5bergaris.JPEG', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN56', 'nama' => 'Label Tom and Jerry No.99', 'harga' => '6000', 'gambar' => 'labeltom&jerryno99.JPG', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN57', 'nama' => 'Stabilo Combo Highlighter CHL 900', 'harga' => '2000', 'gambar' => 'stabilocombohighlighter.JPEG', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN58', 'nama' => 'Joyko Titi Twist Crayon TI-CP-12T', 'harga' => '2500', 'gambar' => 'joykotititwistcrayonticp12t.JPG', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN59', 'nama' => 'Botol Minum', 'harga' => '26000', 'gambar' => 'botolminum.jpg', 'kategori' => 'Living', 'stok' => 1],
            ['kode_menu' => 'MN60', 'nama' => 'Botol Lion Star', 'harga' => '9000', 'gambar' => 'lionstar.jpg', 'kategori' => 'Living', 'stok' => 1],
            ['kode_menu' => 'MN61', 'nama' => 'Sampul Gulung Cokelat 45cm', 'harga' => '12000', 'gambar' => 'sampulgulungcokelat45cm.JPG', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN62', 'nama' => 'Sampul Gulung Plastik', 'harga' => '0', 'gambar' => 'sampulgulungplastik.JPEG', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN63', 'nama' => 'M&G 5m x 5mm Gene Starter Correction Tape with Grip ACT51971', 'harga' => '6000', 'gambar' => 'mgct.JPEG', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN64', 'nama' => 'M&G 6m x 5mm Correction Tape Refill', 'harga' => '4500', 'gambar' => 'refillctmg.JPEG', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN65', 'nama' => 'Kenko Correction Tape', 'harga' => '5500', 'gambar' => 'ctkenko.JPG', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN66', 'nama' => 'Kenko Liquid', 'harga' => '5500', 'gambar' => 'liquidkenko.png', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN67', 'nama' => 'Index Mark Pembatas Buku Joyko IM-60 Tutty Fruity - Watermelon', 'harga' => '8000', 'gambar' => 'indexmarkpembatasbukujoyko.JPG', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN68', 'nama' => 'T&J LABEL FLAGS TRANSPARENT TJ 44-5', 'harga' => '4500', 'gambar' => 't&jlabelflags.JPG', 'kategori' => 'ATK', 'stok' => 0],
            ['kode_menu' => 'MN69', 'nama' => 'Memo Stick / Memo Pelekat Stiker Mms-21 Joyko', 'harga' => '1', 'gambar' => 'joykomemostick.JPEG', 'kategori' => 'ATK', 'stok' => 1],
            ['kode_menu' => 'MN70', 'nama' => 'Gunting lipat portabel mini joyko portable scissors SC-36', 'harga' => '12000', 'gambar' => 'guntinglipatportableminijoyko.JPG', 'kategori' => 'ATK', 'stok' => 0],
            ['kode_menu' => 'MN71', 'nama' => 'M&G Sticky Notes Sakura Times', 'harga' => '7500', 'gambar' => 'mgstickynotessakuratimes.JPG', 'kategori' => 'ATK', 'stok' => 0],
            ['kode_menu' => 'MN72', 'nama' => 'Washi Tape Coasters', 'harga' => '3000', 'gambar' => 'washitapecoasters.JPEG', 'kategori' => 'ATK', 'stok' => 0],
            ['kode_menu' => 'MN73', 'nama' => 'PENGHAPUS HITAM JOYKO SOFT ERASER', 'harga' => '500', 'gambar' => 'joykosofteraser.JPEG', 'kategori' => 'ATK', 'stok' => 0],
            ['kode_menu' => 'MN74', 'nama' => 'Isi pensil mekanik 0.5mm JOYKO PL 05', 'harga' => '2500', 'gambar' => 'isipensilmekanik0.5mmjoykopl05.JPEG', 'kategori' => 'ATK', 'stok' => 23],
        ]);
    }
}
